name: Build and Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: bun run build

      - name: Set Release Tag
        id: check-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" == *-* ]]; then
            echo "npm_tag=rc" >> $GITHUB_OUTPUT
          else
            echo "npm_tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        run: npm publish --provenance --access public --tag ${{ steps.check-tag.outputs.npm_tag }}
